# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
    ##vagrant1.vm.network :hostonly, "192.168.206.130"
    #vagrant1.vm.network "private_network", ip: "192.168.50.4"
    vagrant1.vm.network "private_network", type: "dhcp"
    vagrant1.vm.host_name = "server1.example.com"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 1080
    vagrant1.vm.network "forwarded_port", guest: 8080, host: 1181
    vagrant1.vm.network "forwarded_port", guest: 8081, host: 1182
    vagrant1.vm.network "forwarded_port", guest: 5000, host: 1000
    vagrant1.vm.network "forwarded_port", guest: 443, host: 1443
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    ##vagrant2.vm.network :hostonly, "192.168.206.131"
    #vagrant1.vm.network "private_network", ip: "192.168.50.5"
    vagrant2.vm.network "private_network", type: "dhcp"
    vagrant2.vm.host_name = "desktop1.example.com"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 2081
    vagrant2.vm.network "forwarded_port", guest: 8080, host: 2282
    vagrant2.vm.network "forwarded_port", guest: 8081, host: 2283
    vagrant2.vm.network "forwarded_port", guest: 5000, host: 2000
    vagrant2.vm.network "forwarded_port", guest: 443, host: 2444
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/trusty64"
    ##vagrant3.vm.network :hostonly, "192.168.206.132"
    #vagrant3.vm.network "private_network", ip: "192.168.50.6"
    vagrant3.vm.network "private_network", type: "dhcp"
    vagrant3.vm.host_name = "desktop2.example.com"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 3081
    vagrant3.vm.network "forwarded_port", guest: 8080, host: 3383
    vagrant3.vm.network "forwarded_port", guest: 8081, host: 3384
    vagrant3.vm.network "forwarded_port", guest: 5000, host: 3000
    vagrant3.vm.network "forwarded_port", guest: 443, host: 3444
  end
end
